export const PART_TYPES = [
  'breadboard',
  'breadboard-half',
  'wokwi-arduino-uno',
  'wokwi-led',
  'wokwi-resistor',
  'npn-transistor',
  'rectifier-diode',
  'battery-9v',
  'wokwi-pushbutton',
  'wokwi-slide-switch',
  'wokwi-potentiometer',
  'wokwi-buzzer',
  'wokwi-rgb-led',
  'wokwi-7segment',
  'wokwi-led-bar-graph',
  'wokwi-pushbutton-6mm',
  'wokwi-slide-potentiometer',
  'wokwi-analog-joystick',
  'wokwi-ky-040',
  'wokwi-dip-switch-8',
  'wokwi-membrane-keypad',
  'wokwi-tilt-switch',
  'wokwi-servo',
  'wokwi-stepper-motor',
  'dc-motor',
  'wokwi-ntc-temperature-sensor',
  'wokwi-photoresistor-sensor',
  'wokwi-pir-motion-sensor',
  'wokwi-hc-sr04',
  'wokwi-dht22',
  'wokwi-gas-sensor',
  'wokwi-flame-sensor',
  'wokwi-big-sound-sensor',
  'wokwi-small-sound-sensor',
  'wokwi-heart-beat-sensor',
  'wokwi-ir-receiver',
  'wokwi-ir-remote',
  'wokwi-lcd1602',
  'wokwi-lcd2004',
  'wokwi-ssd1306',
  'wokwi-ds1307',
  'wokwi-mpu6050',
] as const;

export type PartType = (typeof PART_TYPES)[number];